Test_MapScripts::
	.byte 0

Resort_Ini_Letros::
	msgbox Resort_Ini_Letros_Men1, MSGBOX_NPC
	end

Resort_Ini_Esponjo::
	msgbox Resort_Ini_Esponjo_Men1, MSGBOX_NPC
	end	
	
Resort_Ini_Letros_Men1::
	.string "Frander es gey.$"
	
Resort_Ini_Esponjo_Men1::
	.string "La tecnologia es increible.\p"
	.string "Puedo casarme con cualquier vtuber\n"
	.string "aun si no son reales...\p"
	.string "¡QUIERO PONERLA!$"