Test_MapScripts::
	.byte 0

Resort_Ini_Town::
	msgbox Resort_Ini_Town_Men1, MSGBOX_SIGN
	end

Resort_Ini_Esponjo::
	msgbox Resort_Ini_Esponjo_Men1, MSGBOX_SIGN
	end	
	
Resort_Ini_Casa::
	msgbox Resort_Ini_Casa_Men1, MSGBOX_SIGN
	end	
	
Resort_Ini_Town_Men1::
	.string "PUEBLO GENERICO.\n"
	.string "Descripción fea.$"
	
Resort_Ini_Esponjo_Men1::
	.string "La tecnologia es increible.\p"
	.string "Puedo casarme con cualquier vtuber\n"
	.string "aun si no son reales...\p"
	.string "¡QUIERO PONERLA!$"
	
Resort_Ini_Casa_Men1::
	.string "Casa de {PLAYER}.$"	
