language: generic
dist: bionic
sudo: false
env:
  global:
    - DEVKITPRO=$HOME
    - DEVKITARM=$DEVKITPRO/devkitARM
addons:
  apt:
    packages:
      - gcc-multilib
      - linux-libc-dev
cache:
  apt: true
install:
  - pushd $HOME
  - travis_retry wget https://github.com/devkitPro/buildscripts/releases/download/devkitARM_r52/devkitARM_r52-linux.tar.xz
  - tar xJf devkitARM*.tar.xz
  - travis_retry wget https://github.com/devkitPro/devkitarm-rules/releases/download/v1.0.0/devkitarm-rules-1.0.0.tar.xz
  - tar xJf devkitarm-rules-*.tar.xz -C $DEVKITARM
  - travis_retry git clone https://github.com/pret/agbcc.git
  - cd agbcc && ./build.sh && ./install.sh $TRAVIS_BUILD_DIR
  - popd
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: _="Build"
      script:
        - make tools CXX=g++-7
        - make -j2 compare_ruby
        - make -j2 compare_ruby_rev1
        - make -j2 compare_ruby_rev2
        - make -j2 compare_sapphire
        - make -j2 compare_sapphire_rev1
        - make -j2 compare_sapphire_rev2
        - make -j2 modern
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: _="Build Nonmatching"
      script:
        - make tools CXX=g++-7
        - make -j2 ruby NONMATCHING=1
    - os: linux
      addons:
        apt:
          sources:
              - ubuntu-toolchain-r-test
          packages:
            - g++-7
      env: _="Build German"
      before_script:
        - cp override-de.mk override.mk
        - rsync -avhI data-de/ data/
        - rsync -avhI graphics-de/ graphics/
      script:
        - make -j2 tools CXX=g++-7
        - make -j2 compare_ruby_de
        - make -j2 compare_sapphire_de
        - make -j2 compare_ruby_de_debug
after_success:
  - .travis/calcrom/webhook.sh pokeruby
