gAbilityNames:: @ 81FA248
	.string "-------$", 13
	.string "HEDOR$", 13
	.string "LLOVIZNA$", 13
	.string "IMPULSO$", 13
	.string "ARM. BATALLA$", 13
	.string "ROBUSTEZ$", 13
	.string "HUMEDAD$", 13
	.string "FLEXIBILIDAD$", 13
	.string "VELO ARENA$", 13
	.string "ELEC. ESTAT.$", 13
	.string "ABSORBE ELEC$", 13
	.string "ABSORBE AGUA$", 13
	.string "DESPISTE$", 13
	.string "ACLIMATACIÓN$", 13
	.string "OJOCOMPUESTO$", 13
	.string "INSOMNIO$", 13
	.string "CAMBIO COLOR$", 13
	.string "INMUNIDAD$", 13
	.string "ABORSB FUEGO$", 13
	.string "POLVO ESCUDO$", 13
	.string "RITMO PROPIO$", 13
	.string "VENTOSAS$", 13
	.string "INTIMIDACIÓN$", 13
	.string "SOMBRATRAMPA$", 13
	.string "PIEL TOSCA$", 13
	.string "SUPERGUARDA$", 13
	.string "LEVITACIÓN$", 13
	.string "EFECTOESPORA$", 13
	.string "SINCRONÍA$", 13
	.string "CUERPO PURO$", 13
	.string "CURA NATURAL$", 13
	.string "PARARRAYOS$", 13
	.string "DICHA$", 13
	.string "NADO RÁPIDO$", 13
	.string "CLOROFILA$", 13
	.string "ILUMINACIÓN$", 13
	.string "RASTRO$", 13
	.string "POTENCIA$", 13
	.string "PUNTO TÓXICO$", 13
	.string "FOCO INTERNO$", 13
	.string "ESCUDO MAGMA$", 13
	.string "VELO AGUA$", 13
	.string "IMÁN$", 13
	.string "INSONORIZAR$", 13
	.string "CURA LLUVIA$", 13
	.string "CHORRO ARENA$", 13
	.string "PRESIÓN$", 13
	.string "SEBO$", 13
	.string "MADRUGAR$", 13
	.string "CUERPO LLAMA$", 13
	.string "FUGA$", 13
	.string "VISTA LINCE$", 13
	.string "CORTA FUERTE$", 13
	.string "RECOGIDA$", 13
	.string "AUSENTE$", 13
	.string "ENTUSIASMO$", 13
	.string "GRAN ENCANTO$", 13
	.string "MÁS$", 13
	.string "MENOS$", 13
	.string "PREDICCIÓN$", 13
	.string "VISCOSIDAD$", 13
	.string "MUDAR$", 13
	.string "AGALLAS$", 13
	.string "ESCAMA ESP.$", 13
	.string "LODO LÍQUIDO$", 13
	.string "ESPESURA$", 13
	.string "MAR LLAMAS$", 13
	.string "TORRENTE$", 13
	.string "ENJAMBRE$", 13
	.string "CABEZA ROCA$", 13
	.string "SEQUÍA$", 13
	.string "TRAMPA ARENA$", 13
	.string "ESP. VITAL$", 13
	.string "HUMO BLANCO$", 13
	.string "ENERGÍA PURA$", 13
	.string "CAPARAZÓN$", 13
	.string "CACOFONÍA$", 13
	.string "BUCLE AIRE$", 13
