Text_PictureBookshelf: @ 81C6A69
	.string "Hay una colección de libros\n"
	.string "ilustrados de Pokémon."

Text_Bookshelf: @ 81C6A91
	.string "Hay un montón de libros de todo tipo.$"

Text_PokemonCenterBookshelf: @ 81C6AB6
	.string "¡Son revistas sobre Pokémon!\n"
	.string "Nuestros Amigos Pokémon\p"
	.string "Todo sobre los Pokémon\n"
	.string "Esos queridos Pokémon$"

Text_Vase: @ 81C6B00
	.string "Este jarrón parece caro...\n"
	.string "Voy a hechar un ojo dentro...\p"
	.string "Vaya, está vacio.$"

Text_EmptyTrashCan: @ 81C6B41
	.string "No hay nada.$"

Text_ShopShelf: @ 81C6B4D
	.string "Los estantes están repletos de\n"
	.string "todo tipo de articulos Pokémon.$"

Text_Blueprint: @ 81C6B85
	.string "¿Y este plano qué puede ser?\n"
	.string "¡Qué cosa tan rara!$"
