Text_ObtainedTheItem: @ 81A0C68
	.string "¡Obtuvo {STR_VAR_2}!$"

Text_TheBagIsFull:: @ 81A0C79
	.string "La Mochila está llena...$"

Text_PutItemInPocket: @ 81A0C8C
	.string "{PLAYER} puso {STR_VAR_2}\n"
	.string "en el bolsillo de {STR_VAR_3}.$"

Text_FoundOneItem: @ 81A0CB1
	.string "¡{PLAYER} encontró {STR_VAR_2}!$"

Text_TooBadBagIsFull:
	.string "¡Mala suerte!\n"
	.string "La Mochila está llenal...$"

Text_ObtainedTheDecor: @ 81A0CDE
	.string "Obtuvo {STR_VAR_2}.$"

Text_NoRoomLeftForAnother:: @ 81A0CEF
	.string "¡Mala suerte! No queda sitio\n"
	.string "para {STR_VAR_2}...$"

Text_TheDecorWasTransferredToThePC: @ 81A0D1F
	.string "Se envio {STR_VAR_2} al PC.\n"
	
