Text_BootUpPC: @ 81A09EC
	.string "{PLAYER} encendió el PC.$"

Text_WhichPCShouldBeAccessed:: @ 81A0A01
	.string "¿A qué PC quieres acceder?$"

Text_AccessedSomeonesPC: @ 81A0A1E
	.string "Accedió al PC de alguien.$"

Text_StorageSystemOpened: @ 81A0A35
	.string "Acceso al Sistema de Almacenamiento\n"
	.string "de Pokémon concedido.$"

Text_AccessedPlayersPC: @ 81A0A54
	.string "Accedió al PC de {PLAYER}.$"

Text_AccessedLanettesPC: @ 81A0A66
	.string "Accedió al PC de AREDIA.$"
