gText_NurseJoy_Welcome:: @ 81A0A7D
	.string "Hola, éste es el Centro Pokémon.\p"
	.string "Nosotros curamos a los Pokémon\n"
	.string "debilitados.\p"
	.string "¿Quieres que nos ocupemos de los\n"
	.string "Pokémon de tu equipo?$"

gText_NurseJoy_WeHopeToSeeYouAgain:: @ 81A0AFA
	.string "¡Vuelve cuando quieras!$"

gText_NurseJoy_ThankYouForWaiting:: @ 81A0B14
	.string "Gracias por esperar.\p"
	.string "Misión cumplida. Somos especialistas\n"
	.string "en devolver la forma a los Pokémon.$"

UnknownString_81A0B57: @ 81A0B57
	.string "Hola. Éste es el Centro de Cambio\n"
	.string "del Club del Cable Pokémon.$"

UnknownString_81A0B87: @ 81A0B87
	.string "Hola. Éste es el Coliseo del Club\n"
	.string "del Cable Pokémon.$"

UnknownString_81A0BB4: @ 81A0BB4
	.string "Welcome to the POKéMON CABLE CLUB\n"
	.string "TIME CAPSULE.$"
