gSaveText_WouldYouLikeToSave:: @ 81C6C85
UnknownString_81C6C85: @ 81C6C85
	.string "¿Quieres guardar la partida?$"

gSaveText_ThereIsAlreadyAFile:: @ 81C6CA6
UnknownString_81C6CA6: @ 81C6CA6
	.string "Ya existe una partida guardada.\n"
	.string "¿Quieres sobreescribirla?$"

gSaveText_DontTurnOff:: @ 81C6CE1
BattleTower_BattleRoom_Text_1C6CE1:: @ 81C6CE1
	.string "GUARDANDO...\n"
	.string "NO APAGUES LA CONSOLA.$"

gSaveText_PlayerSavedTheGame:: @ 81C6D05
BattleTower_BattleRoom_Text_1C6D05:: @ 81C6D05
	.string "{PLAYER} guardó la partida.$"

UnknownString_81C6D18: @ 81C6D18
	.string "Error al guardar...$"

gSaveText_ThereIsADifferentFile:: @ 81C6D26
UnknownString_81C6D26: @ 81C6D26
	.string "Ya existe otro archivo de\n"
	.string "partida guardada.\p"
	.string "¿Deseas sobreescribirla?$"
