Ranch_MapScripts::
	.byte 0

Ranch_Ini_Aly::
	msgbox Ranch_Ini_Aly_Men1, MSGBOX_NPC
	end
	
Ranch_Ini_Chimmy::
	msgbox Ranch_Ini_Chimmy_Men1, MSGBOX_NPC
	end
	
Ranch_Ini_Yoru::
	msgbox Ranch_Ini_Yoru_Men1, MSGBOX_NPC
	end
	
Ranch_Ini_Aly_Men1::
	.string "'Sonidos de vacio'\n"
	.string "Yo soy su, madre.$"

Ranch_Ini_Chimmy_Men1::
	.string "¡Que no soy gorda!\n"
	.string "Te acusare con mi papi.$"

Ranch_Ini_Yoru_Men1::
	.string "Perdi a mi hija muy mucho si.$"
